version: 2.1

jobs:
  build:
    docker:
      - image: cimg/go:1.20
    steps:
      - checkout
      - run:
          name: "where am i"
          command: "pwd && ls -al"
      - run:
          name: "Install Hugo"
          command: "sudo snap install hugo"
      - run:
          name: "Build Site"
          command: "hugo"
      - persist_to_workspace:
          root: public
          paths:
            - "*"
  deploy:
    docker:
      - image: amazon/aws-cli
    steps:
      - attach_workspace:
          at: /siteData
      - run:
          name: "where am i"
          command: "pwd && ls -al"
      - run:
          name: "Deploy Site"
          command: "aws s3 cp /siteData s3://cold-storage.net"

workflows:
  release:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main
